kinde-oss/js-utils

lib/index.ts
lib/main.test.ts
lib/sessionManager/index.ts
lib/sessionManager/stores/memory.test.ts
lib/sessionManager/stores/memory.ts
lib/sessionManager/types.ts
lib/sessionManager/utils.test.ts
lib/sessionManager/utils.ts
package.json
pnpm-lock.yaml
readme.md

This adds an implementation of a session manager with configuration.  
Currently there is a single manager of `memoryStorage`, more will be added including cookie and session.
The memory manager keys have a default set of keys of `accessToken`, `idToken` and `refreshToken`, this can be added to by passing in an enum as a generic when setting the storage type

feat: Add memory session manager

---

lib/main.test.ts
lib/sessionManager/index.ts
lib/sessionManager/stores/chromeStore.ts
lib/sessionManager/stores/expoSecureStore.test.ts
lib/sessionManager/stores/expoSecureStore.ts
lib/sessionManager/types.ts
package.json
pnpm-lock.yaml
vite.config.ts

This adds support for `expo-secure-store` session store.
- dynamically imports expo-secure-store, not bundled in.
Other small changes
- Correction to JSDocs on chrome store
- Add nonce to StorageKeys
Note: Mocking in place, tests are skipped currently

feat: add expo-secure-store

---

lib/sessionManager/stores/expoSecureStore.ts
lib/types.ts
lib/utils/generateAuthUrl.ts
lib/utils/generateRandomString.ts

- Wait for expo to be loaded before using
- non crypto support for random string generator
- support external nonce generator and removes redundant random generator calls.

Enhancements

---

lib/utils/base64UrlEncode.ts
lib/utils/generateRandomString-nocrypto.test.ts
lib/utils/token/getClaim.ts
lib/utils/token/getClaims.ts
lib/utils/token/getCurrentOrganization.test.ts
lib/utils/token/getCurrentOrganization.ts
lib/utils/token/getDecodedToken.test.ts
lib/utils/token/getDecodedToken.ts
lib/utils/token/getFlag.test.ts
lib/utils/token/getFlag.ts
lib/utils/token/getPermission.test.ts
lib/utils/token/getPermission.ts
lib/utils/token/getPermissions.test.ts
lib/utils/token/getPermissions.ts
lib/utils/token/getRoles.test.ts
lib/utils/token/getRoles.ts
lib/utils/token/getUserOrganistaions.test.ts
lib/utils/token/getUserOrganistaions.ts
lib/utils/token/getUserProfile.test.ts
lib/utils/token/getUserProfile.ts
lib/utils/token/index.ts
lib/utils/token/testUtils/index.ts
package.json
pnpm-lock.yaml
readme.md

Adding token helpers linking to the session manager

feat: token utility helper 

---

lib/main.test.ts
lib/main.ts
lib/utils/token/index.ts

fix: token utilities were not exported
fix: test on exports

fix: token utility export

---

lib/main.test.ts
lib/sessionManager/index.ts
lib/sessionManager/stores/localStorage.test.ts
lib/sessionManager/stores/localStorage.ts

feat: added localStorage store mechism.
Should not be used in production

feat: added localStorage store

---

lib/main.test.ts
lib/types.ts
lib/utils/generateAuthUrl.test.ts
lib/utils/generateAuthUrl.ts
lib/utils/mapLoginMethodParamsForUrl.test.ts

`start_page` was a Kinde implementation to allow the `register` page to be requested as part of the auth url, prior to the spec adding `create` as an option for the `prompt` parameter.
This change removes `start_page` in favour of using `prompt` (this shouldn't cause breaking changes as it is already the way that the PKCE SDK operates)
The inclusion of either `start_page=login` or `prompt=login` will always force Kinde to show the Login screen which often is not desired behaviour. Most of the time founders just wish the SSO session to continue. This PR removes the prompt being added by default and only adds when requested or if the a register auth url link has been requested.
Also fixed a small typo in one of the types
Types and Tests updated
🛟 _If you need help, consider asking for …

Fix `prompt` behaviour

---

lib/utils/isCustomDomain.test.ts
lib/utils/isCustomDomain.ts

Fix an issue where the isCustomDomain check was returning protocol prefixed kinde domains as custom

fix: custom domain with http prefix

---

CHANGELOG.md
lib/sessionManager/stores/localStorage.test.ts
lib/sessionManager/stores/localStorage.ts
lib/utils/exchangeAuthCode.ts
lib/utils/generateAuthUrl.test.ts
lib/utils/generateAuthUrl.ts
lib/utils/isCustomDomain.test.ts
lib/utils/isCustomDomain.ts
lib/utils/token/refreshToken.test.ts
lib/utils/token/refreshToken.ts
package.json

When using on non custom domain `useInsecureForRefreshToken` resulted in access and id token to be stored insecurely

fix: insecure token storage when using no non custom domain

---

lib/utils/token/refreshToken.ts

Fixes an issue with refreshing a token by calling `refreshToken` from a native app. The URLSearchParameters being used in the body of the request need to be converted to a string before being used in the `fetch`, otherwise the fetch will send an empty body, which results in the `oauth/token` endpoint returning a 500 status. 
This behaviour was observed in an react native app on iOS. 
I've patched this change locally and confirmed that the fix resolves the issue.

Stringify the body of the refresh token request

---

lib/utils/exchangeAuthCode.test.ts
lib/utils/exchangeAuthCode.ts

Enhancements to the codeExchange method.
- Stop refresh timer earlier
- Check localStorage refresh token to correctly set the credentials
- Handle the fetch failure better and clear storage.

feat: enhancements to codeExchange

---

lib/utils/refreshTimer.test.ts
lib/utils/refreshTimer.ts

When token expiry is longer than 27 day, this will cause the refreshTimer to instantly resolve.  This forces the SDK to get a new token max every 24 hours.

fix: long token expiry with refresh

---

lib/utils/exchangeAuthCode.ts

After code exchange token refresh timer is started, this adds the callback to be consumed by SDKs and Engineers

feat: notify on token refresh after code exchange

---

lib/main.test.ts
lib/types.ts
lib/utils/checkAuth.test.ts
lib/utils/checkAuth.ts
lib/utils/exchangeAuthCode.ts
lib/utils/token/refreshToken.ts

Exports the RefreshType for better usage of `refreshToken`

feat(types): export RefreshType

---

lib/main.test.ts
lib/main.ts
lib/types.ts
lib/utils/generatePortalUrl.test.ts
lib/utils/generatePortalUrl.ts
lib/utils/index.ts

This renamed the generateProfileUrl with generatePortalUrl to be more consistent with other language 

refactor: renamed generateProfileUrl to generatePortalUrl

---

lib/types.ts
lib/utils/deepMerge.ts
lib/utils/token/accountApi/callAccountApi.ts
lib/utils/token/getEntitlement.test.ts
lib/utils/token/getEntitlement.ts
lib/utils/token/getEntitlements.ts
lib/utils/token/getPermission.ts
lib/utils/token/getPermissions.test.ts
lib/utils/token/getPermissions.ts

Adds an additional parameter to the getPermissions which is an object of options.  Currently there is a single option which takes `forceApi` as a property.
When this is set to `true` it will not look at the token and will use the account API to check the permission for the user.

feat: getPermissions hard check

---

lib/main.test.ts
lib/main.ts
lib/sessionManager/index.ts
lib/sessionManager/types.ts
lib/utils/activityTracking.test.ts
lib/utils/activityTracking.ts
lib/utils/index.ts
lib/utils/token/index.ts

This PR adds automatic activity tracking with session expiry functionality to @kinde/js-utils.
Key additions:
- **sessionManagerActivityProxy** - Wraps any SessionManager with automatic activity tracking
- **updateActivityTimestamp** - Manages activity timers and session cleanup
- Automatic cleanup of sessions when activity timeout expires
- Support for pre-warning callbacks before session expiry
**Recent fixes:**
- Fixed circular dependency between sessionManagerActivityProxy and updateActivityTimestamp 
- Properly bind methods in proxy to maintain correct 'this' context
- Added test coverage to verify proxy method binding works correctly (including destructured methods)
The proxy automatically tracks user activity on session operations and enforces inactivity timeouts, destroying …

feat: add automatic activity tracking with session expiry

---

lib/utils/activityTracking.test.ts
lib/utils/activityTracking.ts

When timeout occurred, `destroySession()` went through the activity proxy, which called `updateActivityTimestamp()`, creating new timers in an infinite loop.
Added regression test `"should fire timeout callbacks only once per inactivity cycle"` that verifies correct behavior and prevents future regressions.

fix: resolve activity tracker infinite timeout loops

---

lib/main.test.ts
lib/main.ts
lib/utils/token/index.ts
lib/utils/token/isAuthenticated.test.ts
lib/utils/token/isAuthenticated.ts
lib/utils/token/isTokenExpired.test.ts
lib/utils/token/isTokenExpired.ts

Added a `isTokenExpired` helper method, updated `isAuthenticated` to use this method

feat: add isTokenExpired method

---

lib/main.test.ts
lib/main.ts
lib/utils/exchangeAuthCode.ts
lib/utils/index.ts
lib/utils/isClient.test.ts
lib/utils/isClient.ts
lib/utils/isServer.test.ts
lib/utils/isServer.ts
lib/utils/refreshTimer.ts
lib/utils/token/refreshToken.ts

This removes the requirement for `window` to exist.  Allows for server side methods to use functions like `refreshToken`
Adds exports for `isClient` and `isServer` helpers

feat: add windowless support to functions

---

lib/utils/checkAuth.test.ts
lib/utils/checkAuth.ts

Fix issue where is an empty active storage exists when checking auth, this will cause refresh to fail.

fix: empty storage authCheck + tests

---

lib/sessionManager/stores/chromeStore.ts
lib/sessionManager/stores/expoSecureStore.ts
lib/sessionManager/stores/localStorage.test.ts
lib/sessionManager/stores/localStorage.ts
lib/sessionManager/stores/memory.test.ts
lib/sessionManager/stores/memory.ts
lib/sessionManager/types.ts

Added a subscription pattern to `SessionBase` so you can listen for changes. You can now subscribe to storage updates and do something when things change. Also added some smart batching using microtasks so we don't spam listeners when multiple operations happen at once.
Tests have been updated to comprehensively test:
- Listeners trigger on set/remove/destroy
- Multiple listeners work fine
- Async listeners are supported
- Mix of sync and async listeners
- Unsubscribe works as expected
- Batching multiple sync operations
- Can't accidentally subscribe twice (using Set)
- Can unsubscribe specific listeners
- Batch operations like setItems work
- Microtask boundary behavior
Chrome Storage and Expo Secure Store tests have been omitted for the time being as they're skipped entirely. …

feat: add store listener/subscription mechanism

---

lib/sessionManager/types.ts
lib/utils/token/refreshToken.test.ts
lib/utils/token/refreshToken.ts

To better support various libraries namely backend libraries, allow the consumer to override and supply a custom implementation on how the tokens are refreshed.
```
storageSettings.onRefreshHandler: () -> {
// Refresh code goes here.
}
```
This will update relevant storages and start refresh timers as required.

feat: add onRefreshHandler to custom handle token refreshes
