kinde-oss/js-utils

lib/types.ts, lib/utils/generateAuthUrl.test.ts
fix incorrect value from offline scope
=> fix: offline scope

lib/types.ts, lib/utils/mapLoginMethodParamsForUrl.ts
Adds workflow and release Id as auth params
=> feat: add workflowId and ReleaseId query params

pnpm-lock.yaml, vite.config.ts
Fixes issue when using package caused a dependancy of `react-native` when it wasn't required.
=> fix: incorrect react-native requirement

lib/types.ts, lib/utils/mapLoginMethodParamsForUrl.ts
corrects the parameter for the workflow deployment id
=> fix: deployment id url parameter

lib/main.test.ts, lib/utils/index.ts
expose refresh timer handlers.
=> feat: export refresh timer methods

lib/utils/exchangeAuthCode.test.ts, lib/utils/exchangeAuthCode.ts
Extend metrics to include language and framework version
=> feat: update SDK usage matrics

lib/utils/token/getClaim.ts, lib/utils/token/getClaims.ts
Extends `getClaim` and `getClaims` to get claims from either id or access token
=> feat: get claims from either token

lib/utils/token/getFlag.test.ts, lib/utils/token/getFlag.ts
Fix incorrect handling of boolean feature flag with additional tests covering the failed state
=> fix: false boolean flag returning null

lib/types.ts, lib/utils/token/getUserProfile.ts
Allow not app params to be passed to the login method.
=> fix: loginMethodParams now a Partial

lib/utils/generateAuthUrl.test.ts, lib/utils/generateAuthUrl.ts, lib/utils/mapLoginMethodParamsForUrl.ts
In some instances the redirect url should not be sanitised, e.g. Expo, this provides option to prevent that happening
=> feat: Add option to disable url sanitation

lib/utils/token/getDecodedToken.ts, lib/utils/token/getRoles.ts, lib/utils/token/index.ts
Role type was not exported and getRole docs were wrong
=> fix: role docs and type exports

lib/utils/token/refreshToken.test.ts, lib/utils/token/refreshToken.ts
When token refresh occurs trigger callback
=> feat: add callback to refresh token method.

eslint.config.js
Fixed warnings in generated code.
=> chore: eslint ignore updates

lib/main.ts, lib/sessionManager/index.ts, lib/tests/appBundling.test.ts, lib/tests/expoLazyLoading.test.ts, lib/utils/index.ts, lib/utils/token/index.ts, package.json
- Improves treeshaking
- code splits expo-secure-store as dependancy
=> feat: improve treeshaking and lazy loading of expo-secure-store

.github/workflows/build-test-ci.yml, pnpm-lock.yaml
Update the pnpm setup action to the same version used.
=> ci: update setup action version

lib/types.ts, lib/utils/generateAuthUrl.test.ts, lib/utils/generateAuthUrl.ts
Adds support for marketing properties to be applied to the user
https://docs.kinde.com/properties/work-with-properties/marketing-tags-properties/
=> feat: marketing tag properties

lib/main.test.ts, lib/main.ts, lib/utils/token/getRawToken.test.ts, lib/utils/token/getRawToken.ts, lib/utils/token/index.ts
=> feat: getRawToken

lib/utils/exchangeAuthCode.test.ts, lib/utils/exchangeAuthCode.ts, lib/utils/token/refreshToken.test.ts, lib/utils/token/refreshToken.ts
correct a typo in error message
=> fix: correct typo in error message

lib/types.ts, lib/utils/mapLoginMethodParamsForUrl.ts
=> feat: plan interest

lib/types.ts, lib/utils/generateAuthUrl.test.ts, lib/utils/generateAuthUrl.ts, lib/utils/mapLoginMethodParamsForUrl.test.ts, lib/utils/mapLoginMethodParamsForUrl.ts, lib/utils/snakeToCamelCase.test.ts, lib/utils/snakeToCamelCase.ts
This adds support for reauth, this allows JS libraries to recover and restart auth when auth page has been bookmarked
=> feat: support reauth functionality

lib/utils/generatePortalUrl.test.ts, lib/utils/generatePortalUrl.ts
This implementation allows for any type or return url not just web urls
=> fix: portal return URL validation

lib/types.ts, lib/utils/mapLoginMethodParamsForUrl.ts
Adds pages mode auth parameter to the types and converter
=> feat: add pages mode auth param

lib/types.ts
Added extra portal pages to the PortalPage enum
=> feat: add extra PortalPages

lib/main.test.ts, lib/main.ts, lib/sessionManager/index.ts
=> feat: export sessionBase

lib/utils/exchangeAuthCode.test.ts, lib/utils/exchangeAuthCode.ts
Add ability to pass in the clientSecret to the code exchange.
=> feat: add secret to exchangeAuthCode.

lib/utils/checkAuth.ts
When the storage has tokens already, checkAuth will use these and refresh if required.
=> feat: checkAuth when tokens in storage
